spring.datasource.url=jdbc:sqlite:mypile.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.profiles.active=local
tmdb.api.key=${TMDB_API_KEY:placeholder}
rawg.api.key=${RAWG_API_KEY:placeholder}